version: '3'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    platform: linux/amd64  # 플랫폼을 명시적으로 지정
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8089:8080"