groups:
  - name: zero-alerts
    interval: 10s
    limit: 0
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."



